// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerIW3VLSr0lFiMx6Wynode2NOTZVQgOY',
    appId: '1:843812586508:web:your_web_app_id',
    messagingSenderId: '843812586508',
    projectId: 'eduguide-3e841',
    authDomain: 'eduguide-3e841.firebaseapp.com',
    storageBucket: 'eduguide-3e841.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerIW3VLSr0lFiMx6Wynode2NOTZVQgOY',
    appId: '1:843812586508:android:c6c4d96937815586605a29',
    messagingSenderId: '843812586508',
    projectId: 'eduguide-3e841',
    storageBucket: 'eduguide-3e841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerIW3VLSr0lFiMx6Wynode2NOTZVQgOY',
    appId: '1:843812586508:ios:your_ios_app_id',
    messagingSenderId: '843812586508',
    projectId: 'eduguide-3e841',
    storageBucket: 'eduguide-3e841.firebasestorage.app',
    iosBundleId: 'com.example.eduguideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDerIW3VLSr0lFiMx6Wynode2NOTZVQgOY',
    appId: '1:843812586508:ios:your_ios_app_id',
    messagingSenderId: '843812586508',
    projectId: 'eduguide-3e841',
    storageBucket: 'eduguide-3e841.firebasestorage.app',
    iosBundleId: 'com.example.eduguideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDerIW3VLSr0lFiMx6Wynode2NOTZVQgOY',
    appId: '1:843812586508:web:your_web_app_id',
    messagingSenderId: '843812586508',
    projectId: 'eduguide-3e841',
    authDomain: 'eduguide-3e841.firebaseapp.com',
    storageBucket: 'eduguide-3e841.firebasestorage.app',
  );
}
